namespace import -force msgcat::mcset

mcset en file File
mcset en open Open
mcset en close Close
mcset en quit Quit
mcset en volume volume
mcset en play play
mcset en pause pause
mcset en prevKeyFrame "prev. key frame"
mcset en nextKeyFrame "next key frame"
mcset en mute mute
mcset en unmute unmute
mcset en freezeFrame freeze-frame
mcset en dryRun "dry run"
mcset en cut clip
mcset en delete delete
mcset en run run
mcset en confirmDeleteTitle "delete jobs from list"
mcset en confirmDeleteQuestion "Are you sure want to delete selected jobs from the list?"
mcset en confirmCloseQuestion "Task list is not empty. Are you sure you want to close the session?"
mcset en confirmExitQuestion "Task list is not empty. Are you sure you want to quit?"
mcset en manualInput "manual input"
mcset en add "add to jobs"
mcset en loading "loading file..."
mcset en yes "YES"
mcset en no "NO"
mcset en confirmDeleteTitle "delete jobs from list"
mcset en confirmDeleteQuestion "Are you sure want to delete selected jobs from the list?"
mcset en confirmExitQuestion "Task list is not empty. Are you sure you want to quit?"
mcset en executing "executing jobs..."
mcset en ffmpegFail "failed to execute ffmpeg command (see ffmpeg-YYYYMMDD-HHMMSS.log)"
mcset en noKeyFrames "failed to get keyframes list"
mcset en noSound "no sound"
mcset en add "add to jobs"
mcset en invalidJobStr "invalid line"
mcset en reencode "reencode"
