namespace import -force msgcat::mcset

mcset ru file Файл
mcset ru open Открыть
mcset ru close Закрыть
mcset ru quit Выйти
mcset ru volume громкость
mcset ru play воспроизведение
mcset ru pause пауза
mcset ru prevKeyFrame "пред. опорный кадр"
mcset ru nextKeyFrame "след. опорный кадр"
mcset ru mute "выкл. звук"
mcset ru unmute "вкл. звук"
mcset ru freezeFrame стоп-кадр
mcset ru dryRun "пробный запуск"
mcset ru cut вырезать
mcset ru delete удалить
mcset ru run старт
mcset ru confirmDeleteTitle "удаление заданий из списка"
mcset ru confirmDeleteQuestion "Желаете удалить выделенные задания из списка?"
mcset ru confirmCloseQuestion "Список заданий непуст. Действительно ли вы хотите закрыть сессию?"
mcset ru confirmExitQuestion "Список заданий непуст. Действительно ли вы хотите выйти?"
mcset ru manualInput "ручной ввод"
mcset ru add "добавить в задания"
mcset ru loading "загрузка файла..."
mcset ru yes "ДА"
mcset ru no "НЕТ"
mcset ru confirmDeleteTitle "удаление заданий из списка"
mcset ru confirmDeleteQuestion "Желаете удалить выделенные задания из списка?"
mcset ru confirmExitQuestion "Список заданий непуст. Действительно ли вы хотите выйти?"
mcset ru executing "задания выполняются..."
mcset ru ffmpegFail "не удалось выполнить команду ffmpeg (см. ffmpeg-YYYYMMDD-HHMMSS.log)"
mcset ru noKeyFrames "не удалось получить список опорных кадров"
mcset ru noSound "без звука"
mcset ru add "добавить в задания"
mcset ru invalidJobStr "некорректная строка"
mcset ru reencode "перекодировать"
